# Generated by Django 2.0.7 on 2018-07-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=10)),
                ('Pcost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Pmfdt', models.DateField()),
                ('Pexpdt', models.DateField()),
            ],
        ),
    ]
